# cloudbuild.yaml
images:
  - us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:$SHORT_SHA
  - us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:latest

steps:
  # (optional) warm cache
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker pull us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:latest || true

  # build with two tags
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t","us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:$SHORT_SHA",
        "-t","us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:latest",
        "."
      ]

  # push both tags
  - name: gcr.io/cloud-builders/docker
    args: ["push","us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:$SHORT_SHA"]
  - name: gcr.io/cloud-builders/docker
    args: ["push","us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:latest"]

  # deploy latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy staticsite-service \
          --image us-central1-docker.pkg.dev/plexiform-plane-459218-a7/staticsite/staticsite:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
